name = "SubspaceClustering"
uuid = "bea3bcab-479e-4b6c-b047-c6cd33cd022c"
authors = ["David Hong <hong@udel.edu> and contributors"]
version = "0.1.0"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ArnoldiMethod = "0.4.0"
Clustering = "0.15.8"
Compat = "3.47.0, 4.10.0"
LinearAlgebra = "1.10"
Logging = "1.10"
ProgressLogging = "0.1.4"
Random = "1.10"
SparseArrays = "1.10"
julia = "1.10"
